# Perturb Translations
In this notebook, we develop a method for perturbing the translation of the dataset positions.

## Load up the colmap dataset

In [2]:
import utils.subset
from pycolmap import Reconstruction

import utils.vis.plot_colmap

%load_ext autoreload
%autoreload 2

import pycolmap
import pathlib

model_path = pathlib.Path('./output/01_nerf/02_lego_large/1762043798762/0')

# Load the reconstruction
reconstruction = pycolmap.Reconstruction(model_path)

# Print basic info about the reconstruction
print(f"Number of registered images: {len(reconstruction.images)}")
print(f"Number of 3D points: {len(reconstruction.points3D)}")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Number of registered images: 69
Number of 3D points: 6672


In [3]:
# Create two disjoint image subsets from the reconstruction
import utils.subset
subgraph_a_image_ids, subgraph_b_image_ids = utils.subset.sample_image_subsets(reconstruction)

In [4]:
import utils.vis

# Render the two subsets
utils.vis.plot_image_subsets(reconstruction, subgraph_a_image_ids, subgraph_b_image_ids)

## Visualize pyG in 3D

In [28]:
# Create the PyG dataset for each subgraph
import utils.subset

graph_a = utils.subset.reconstruction_to_pyg_data(reconstruction, subgraph_a_image_ids)
graph_b = utils.subset.reconstruction_to_pyg_data(reconstruction, subgraph_b_image_ids)

In [29]:
graph_a.x

tensor([[-5.0561e-01,  1.4473e+00, -1.9871e+00],
        [-8.7134e-01,  1.0277e+00, -2.0362e+00],
        [-1.4425e+00,  1.2606e-01, -1.9379e+00],
        [-1.2084e+00,  4.3559e+00, -5.2545e-01],
        [-7.2209e-01, -1.1619e+00, -1.4978e+00],
        [ 3.3094e+00,  4.6423e-02,  1.3857e+00],
        [-1.9203e+00, -4.3835e-01, -1.7161e+00],
        [-1.9794e+00, -8.2072e-01, -1.5525e+00],
        [ 4.0640e-01, -3.8644e-01, -1.5990e+00],
        [ 2.9078e+00,  1.2795e+00,  2.0859e-01],
        [ 8.5093e-01,  1.3613e+00, -1.6269e+00],
        [ 1.6326e+00,  5.3027e-01, -1.1720e+00],
        [ 1.2489e+00, -1.5448e+00, -5.4317e-01],
        [ 2.3029e+00,  2.9319e-01, -5.4084e-01],
        [ 1.3289e-01, -2.3562e+00, -3.7942e-01],
        [ 1.8422e+00,  1.8071e+00, -9.3744e-01],
        [ 2.7129e+00,  1.3970e+00, -7.6284e-02],
        [ 2.7291e+00,  2.0130e+00,  1.3224e-01],
        [ 2.6687e+00,  2.2047e+00,  1.2840e-01],
        [ 1.0929e+00,  4.0290e+00, -1.3308e-01],
        [ 1.8724e+00

In [30]:
# Perturb data
import torch
graph_a.x + torch.tensor([1, 2, 3])


tensor([[ 0.4944,  3.4473,  1.0129],
        [ 0.1287,  3.0277,  0.9638],
        [-0.4425,  2.1261,  1.0621],
        [-0.2084,  6.3559,  2.4745],
        [ 0.2779,  0.8381,  1.5022],
        [ 4.3094,  2.0464,  4.3857],
        [-0.9203,  1.5617,  1.2839],
        [-0.9794,  1.1793,  1.4475],
        [ 1.4064,  1.6136,  1.4010],
        [ 3.9078,  3.2795,  3.2086],
        [ 1.8509,  3.3613,  1.3731],
        [ 2.6326,  2.5303,  1.8280],
        [ 2.2489,  0.4552,  2.4568],
        [ 3.3029,  2.2932,  2.4592],
        [ 1.1329, -0.3562,  2.6206],
        [ 2.8422,  3.8071,  2.0626],
        [ 3.7129,  3.3970,  2.9237],
        [ 3.7291,  4.0130,  3.1322],
        [ 3.6687,  4.2047,  3.1284],
        [ 2.0929,  6.0290,  2.8669],
        [ 2.8724,  5.7133,  3.2984],
        [-0.1966,  5.6422,  1.8321],
        [ 1.3296,  6.1331,  2.5122],
        [-1.4336,  4.7192,  1.5650],
        [ 2.6326, -0.5481,  4.3328],
        [ 0.1786,  6.6678,  2.8509],
        [ 0.6422,  6.7095,  2.9842],
 

In [55]:
# Clone the graph so we don't affect graph_a
graph_c = graph_a.clone()
# Scale
# graph_c.x = graph_c.x * 0.5
# Translate
graph_c.x = graph_c.x + torch.tensor([1, 2, 3])

In [56]:
graph_c.x

tensor([[ 0.4944,  3.4473,  1.0129],
        [ 0.1287,  3.0277,  0.9638],
        [-0.4425,  2.1261,  1.0621],
        [-0.2084,  6.3559,  2.4745],
        [ 0.2779,  0.8381,  1.5022],
        [ 4.3094,  2.0464,  4.3857],
        [-0.9203,  1.5617,  1.2839],
        [-0.9794,  1.1793,  1.4475],
        [ 1.4064,  1.6136,  1.4010],
        [ 3.9078,  3.2795,  3.2086],
        [ 1.8509,  3.3613,  1.3731],
        [ 2.6326,  2.5303,  1.8280],
        [ 2.2489,  0.4552,  2.4568],
        [ 3.3029,  2.2932,  2.4592],
        [ 1.1329, -0.3562,  2.6206],
        [ 2.8422,  3.8071,  2.0626],
        [ 3.7129,  3.3970,  2.9237],
        [ 3.7291,  4.0130,  3.1322],
        [ 3.6687,  4.2047,  3.1284],
        [ 2.0929,  6.0290,  2.8669],
        [ 2.8724,  5.7133,  3.2984],
        [-0.1966,  5.6422,  1.8321],
        [ 1.3296,  6.1331,  2.5122],
        [-1.4336,  4.7192,  1.5650],
        [ 2.6326, -0.5481,  4.3328],
        [ 0.1786,  6.6678,  2.8509],
        [ 0.6422,  6.7095,  2.9842],
 

In [57]:
utils.vis.plot_3D_graph(graph_c, graph_b)