# Perturb Translations
In this notebook, we develop a method for perturbing the translation of the dataset positions.

## Load up the colmap dataset

In [1]:
import utils.subset
from pycolmap import Reconstruction

import utils.vis.plot_colmap

%load_ext autoreload
%autoreload 2

import pycolmap
import pathlib

model_path = pathlib.Path('./output/01_nerf/02_lego_large/1762043798762/0')

# Load the reconstruction
reconstruction = pycolmap.Reconstruction(model_path)

# Print basic info about the reconstruction
print(f"Number of registered images: {len(reconstruction.images)}")
print(f"Number of 3D points: {len(reconstruction.points3D)}")

Number of registered images: 69
Number of 3D points: 6672


In [2]:
# Create two disjoint image subsets from the reconstruction
import utils.subset
subgraph_a_image_ids, subgraph_b_image_ids = utils.subset.sample_image_subsets(reconstruction)

In [10]:
import utils.vis

# Render the two subsets
utils.vis.plot_image_subsets(reconstruction, subgraph_a_image_ids, subgraph_b_image_ids)

## Visualize pyG in 3D

In [11]:
# Create the PyG dataset for each subgraph
import utils.subset

graph_a = utils.subset.reconstruction_to_pyg_data(reconstruction, subgraph_a_image_ids)
graph_b = utils.subset.reconstruction_to_pyg_data(reconstruction, subgraph_b_image_ids)

In [12]:
graph_a.x

tensor([[-1.4210e+00,  1.0983e+00, -2.0178e+00],
        [-5.0561e-01,  1.4473e+00, -1.9871e+00],
        [-8.7134e-01,  1.0277e+00, -2.0362e+00],
        [-1.4425e+00,  1.2606e-01, -1.9379e+00],
        [-1.2084e+00,  4.3559e+00, -5.2545e-01],
        [-7.2209e-01, -1.1619e+00, -1.4978e+00],
        [-1.6856e+00,  1.8505e+00, -1.8977e+00],
        [-1.1060e+00,  2.3858e+00, -1.8104e+00],
        [-6.8548e-01,  2.8489e+00, -1.6200e+00],
        [-1.9203e+00, -4.3835e-01, -1.7161e+00],
        [-1.9794e+00, -8.2072e-01, -1.5525e+00],
        [-2.8840e+00, -3.1359e-01, -1.4222e+00],
        [-2.1811e-01, -3.6868e-01, -1.7666e+00],
        [ 4.0640e-01, -3.8644e-01, -1.5990e+00],
        [ 5.5233e-01, -4.7632e-01, -1.5144e+00],
        [ 2.9078e+00,  1.2795e+00,  2.0859e-01],
        [ 1.2949e+00, -3.7219e-01, -1.1836e+00],
        [ 8.5093e-01,  1.3613e+00, -1.6269e+00],
        [ 1.2489e+00, -1.5448e+00, -5.4317e-01],
        [ 2.3029e+00,  2.9319e-01, -5.4084e-01],
        [ 6.2725e-01

In [13]:
# Perturb data
import torch
graph_a.x + torch.tensor([1, 2, 3])


tensor([[-0.4210,  3.0983,  0.9822],
        [ 0.4944,  3.4473,  1.0129],
        [ 0.1287,  3.0277,  0.9638],
        [-0.4425,  2.1261,  1.0621],
        [-0.2084,  6.3559,  2.4745],
        [ 0.2779,  0.8381,  1.5022],
        [-0.6856,  3.8505,  1.1023],
        [-0.1060,  4.3858,  1.1896],
        [ 0.3145,  4.8489,  1.3800],
        [-0.9203,  1.5617,  1.2839],
        [-0.9794,  1.1793,  1.4475],
        [-1.8840,  1.6864,  1.5778],
        [ 0.7819,  1.6313,  1.2334],
        [ 1.4064,  1.6136,  1.4010],
        [ 1.5523,  1.5237,  1.4856],
        [ 3.9078,  3.2795,  3.2086],
        [ 2.2949,  1.6278,  1.8164],
        [ 1.8509,  3.3613,  1.3731],
        [ 2.2489,  0.4552,  2.4568],
        [ 3.3029,  2.2932,  2.4592],
        [ 1.6272, -0.2139,  2.6989],
        [ 1.1329, -0.3562,  2.6206],
        [ 0.1807,  0.0075,  2.0631],
        [-1.4648,  0.5354,  1.9576],
        [ 2.3789,  4.8485,  2.1221],
        [ 2.1616,  5.5974,  2.4892],
        [ 2.0929,  6.0290,  2.8669],
 

In [14]:
# Clone the graph so we don't affect graph_a
graph_c = graph_a.clone()
# Scale
# graph_c.x = graph_c.x * 0.5
# Translate
graph_c.x = graph_c.x + torch.tensor([1, 2, 3])

In [15]:
graph_c.x

tensor([[-0.4210,  3.0983,  0.9822],
        [ 0.4944,  3.4473,  1.0129],
        [ 0.1287,  3.0277,  0.9638],
        [-0.4425,  2.1261,  1.0621],
        [-0.2084,  6.3559,  2.4745],
        [ 0.2779,  0.8381,  1.5022],
        [-0.6856,  3.8505,  1.1023],
        [-0.1060,  4.3858,  1.1896],
        [ 0.3145,  4.8489,  1.3800],
        [-0.9203,  1.5617,  1.2839],
        [-0.9794,  1.1793,  1.4475],
        [-1.8840,  1.6864,  1.5778],
        [ 0.7819,  1.6313,  1.2334],
        [ 1.4064,  1.6136,  1.4010],
        [ 1.5523,  1.5237,  1.4856],
        [ 3.9078,  3.2795,  3.2086],
        [ 2.2949,  1.6278,  1.8164],
        [ 1.8509,  3.3613,  1.3731],
        [ 2.2489,  0.4552,  2.4568],
        [ 3.3029,  2.2932,  2.4592],
        [ 1.6272, -0.2139,  2.6989],
        [ 1.1329, -0.3562,  2.6206],
        [ 0.1807,  0.0075,  2.0631],
        [-1.4648,  0.5354,  1.9576],
        [ 2.3789,  4.8485,  2.1221],
        [ 2.1616,  5.5974,  2.4892],
        [ 2.0929,  6.0290,  2.8669],
 

In [28]:
utils.vis.plot_3D_graph(graph_a, graph_b)

In [16]:
utils.vis.plot_3D_graph(graph_c, graph_b)

# Visualize whole graph

In [23]:
graph_complete = utils.subset.reconstruction_to_pyg_data(reconstruction)
graph_dummy = utils.subset.reconstruction_to_pyg_data(reconstruction,)


In [27]:
utils.vis.plot_3D_graph(graph_complete, graph_dummy)